include:
- template: Dependency-Scanning.gitlab-ci.yml

image: golang:1.14

stages:
- dependencies
- test

workflow:
  rules:
  - if: $CI_MERGE_REQUEST_ID
  - if: $CI_COMMIT_BRANCH == "master"
  - if: $CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/

.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  before_script:
  - mkdir -p .go
  cache:
    paths:
    - .go/pkg/mod/

gomod:
  stage: dependencies
  extends: .go-cache
  script:
  - go mod download

lint:
  stage: test
  extends: .go-cache
  image: golangci/golangci-lint:v1.27.0
  script:
  - golangci-lint run -v --timeout 4m --skip-dirs '(^|/).go($|/)'

test:
  stage: test
  extends: .go-cache
  script:
  - ./bin/test.sh

test-build:
  stage: test
  extends: .go-cache
  script:
  - ./bin/build.sh
  - ./eks-auth-sync -version
