image: golang:1.14

stages:
- dependencies
- test

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
  - /go/pkg

workflow:
  rules:
  - if: $CI_MERGE_REQUEST_ID
  - if: $CI_COMMIT_BRANCH == "master"

gomod:
  stage: dependencies
  script:
  - go mod download

lint:
  stage: test
  image: golangci/golangci-lint:v1.27.0
  script:
  - golangci-lint run -v

test:
  stage: test
  script:
  - ./bin/test.sh

docker-image-build:
  stage: test
  image: docker:latest
  services:
  - docker:dind
  script:
  - ./bin/docker-build.sh "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"