before:
  hooks:
    - go mod download
builds:
- main: ./cmd/eksauthsync
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm
  - arm64
  ldflags:
  - -s -w
  - -X gitlab.com/polarsquad/eks-auth-sync/internal/buildinfo.Version={{ .Version }}
  - -X gitlab.com/polarsquad/eks-auth-sync/internal/buildinfo.GitHash={{ .Commit }}
dockers:
- goos: linux
  goarch: amd64
  binaries:
  - eks-auth-sync
  image_templates:
  - registry.gitlab.com/polarsquad/{{ .ProjectName }}:{{ .Version }}
  - registry.gitlab.com/polarsquad/{{ .ProjectName }}:latest
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
release:
  gitlab:
    owner: polarsquad
    name: eks-auth-sync
  name_template: "{{.ProjectName}}-v{{.Version}}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Major }}.{{ .Minor }}.{{ .Patch }}-{{ .ShortCommit }}"
changelog:
  skip: true
